Repository embrace-io/embrace-web-sdk, pull requests merged in 2025-04, with the labels that each got.

#273 fix: do not use opentelemetry 0.200.x versions
  demo/frontend-cdn/package-lock.json
  demo/frontend/package-lock.json
  package-lock.json
  package.json
Labels: fix, patch

#274 ci: give github action permissions to write to the repo at the job level
  .github/workflows/ci-nodejs.yml
Labels: maintenance, patch

#275 fix: code injection vulnerability
  .github/workflows/ci-nodejs.yml
Labels: fix, patch

#278 fix: typo in CDN code snippet
  README.md
Labels: fix, patch

#276 chore: re-export Span
  src/sdk/index.ts
Labels: maintenance, patch

#277 chore: protect against the SDK being initialized multiple times
  src/sdk/initSDK.test.ts
  src/sdk/initSDK.ts
  src/sdk/registry.ts
  src/sdk/types.ts
Labels: maintenance, patch

#283 chore: make app version optional during cli processing
  cli/src/index.ts
  cli/src/processSourceFiles.ts
  cli/src/validateInput.ts
Labels: maintenance, patch

#284 chore: bump version to 0.0.16
  cli/package-lock.json
  cli/package.json
  cli/src/constants.ts
  demo/frontend/package-lock.json
  package-lock.json
  package.json
  src/resources/constants/index.ts
Labels: maintenance, patch

#285 fix: web-cli bin name changed, update the demo
  demo/frontend/package-lock.json
  demo/frontend/package.json
Labels: fix, patch

#287 test: move initSDK test, add verify export of custom spans and logs
  src/sdk/initSDK.test.ts
Labels: maintenance, patch

#291 ci: disable release of major versions until we go out of beta
  .github/release-drafter.yml
Labels: maintenance, major, patch

#292 ci: new workflow to manually trigger releases going through a PR
  .github/release-drafter.yml
  .github/workflows/ci-nodejs.yml
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
  DEVELOPING.md
  commitlint.config.js
Labels: maintenance, patch

#286 chore: document how data is exported
  DATA_EXPORT.md
  README.md
  src/processors/EmbraceSessionBatchedSpanProcessor/EmbraceSessionBatchedSpanProcessor.test.ts
  src/processors/EmbraceSessionBatchedSpanProcessor/EmbraceSessionBatchedSpanProcessor.ts
  src/transport/RetryingTransport/constants.ts
Labels: maintenance, patch

#294 chore: bump version
  cli/package-lock.json
  cli/package.json
  cli/src/constants.ts
  demo/frontend/package-lock.json
  package-lock.json
  package.json
  src/resources/constants/index.ts
Labels: maintenance, patch

#295 fix: checkout new branch during release workflow
  .github/workflows/release.yaml
Labels: fix, patch

#296 fix: disable releaser when the commit does NOT start with release
  .github/workflows/release-drafter.yaml
Labels: fix, patch

#298 fix: add more permissions to release action
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
Labels: fix, patch

#300 ci: add constant files changes to the release PR
  .github/workflows/release.yaml
Labels: maintenance, patch

#302 fix: adjust commit msg to make commitlint happy
  .github/workflows/release.yaml
Labels: fix, patch

#304 ci: setup action to production if a release is created, not only if published
  .github/workflows/ci-nodejs.yml
Labels: maintenance, patch

#306 ci: make the publishing of the release a manual step
  .github/workflows/ci-nodejs.yml
  .github/workflows/release-drafter.yaml
  DEVELOPING.md
Labels: maintenance, patch

#309 chore: clarify various behaviours in README and cover with tests
  README.md
  demo/frontend/src/App.tsx
  demo/frontend/src/otel.ts
  src/managers/EmbraceUserManager/EmbraceUserManager.test.ts
  src/sdk/initSDK.test.ts
  src/testUtils/FailingStorage/FailingStorage.ts
  src/testUtils/FailingStorage/index.ts
  src/testUtils/index.ts
Labels: maintenance, patch

#315 docs: adjust cdn version recommendation
  README.md
Labels: maintenance, patch

#322 ci: prefix semser version level to avoid conflict with dependabot
  .github/release-drafter.yml
Labels: maintenance, fix, patch

#310 chore: additional API for indicating a span failed
  README.md
  src/api-traces/api/TraceAPI/TraceAPI.ts
  src/api-traces/api/TraceAPI/index.ts
  src/api-traces/api/TraceAPI/types.ts
  src/api-traces/api/index.ts
  src/api-traces/index.ts
  src/api-traces/manager/NoOpTraceManager/NoOpTraceManager.test.ts
  src/api-traces/manager/NoOpTraceManager/NoOpTraceManager.ts
  src/api-traces/manager/ProxyTraceManager/ProxyTraceManager.test.ts
  src/api-traces/manager/ProxyTraceManager/ProxyTraceManager.ts
  src/api-traces/manager/types.ts
  src/constants/attributes.ts
  src/constants/index.ts
  src/index.ts
  src/managers/EmbraceTraceManager/EmbracePerformanceSpan.ts
  src/managers/EmbraceTraceManager/EmbraceTraceManager.test.ts
  src/managers/EmbraceTraceManager/EmbraceTraceManager.ts
Labels: maintenance, semver-patch

#332 fix: validate tests types during cicd integration, fix existing failing type checks
  .gitignore
  package.json
  src/api-logs/api/LogAPI/LogAPI.test.ts
  src/api-logs/manager/NoOpLogManager/NoOpLogManager.test.ts
  src/api-logs/manager/ProxyLogManager/ProxyLogManager.test.ts
Labels: maintenance, fix, semver-patch

#331 EMBR-7452 chore: include app instance id as part of the resource
  src/constants/attributes.ts
  src/constants/index.ts
  src/managers/EmbraceUserManager/EmbraceUserManager.test.ts
  src/managers/EmbraceUserManager/EmbraceUserManager.ts
  src/resources/appInstanceId.ts
  src/resources/constants/index.ts
  src/resources/types.ts
  src/resources/webSdkResource.test.ts
  src/resources/webSdkResource.ts
  src/sdk/initSDK.ts
Labels: maintenance, semver-patch
