Repository embrace-io/embrace-web-sdk, pull requests merged in 2025-09, with the labels that each got.

#718 chore(eslint): add scripts and tests
  eslint.config.mjs
  scripts/measureSize.ts
  tests/integration/config/index.ts
  tests/integration/utils/run-e2e-tests.ts
  tests/integration/utils/run-platform-smoke-test.ts
  tests/performance/api/server.ts
  tests/performance/config/index.ts
  tests/performance/config/thresholds.ts
  tests/performance/tests/lighthouse-startup-performance-tests.spec.ts
  tests/utils/json-to-markdown-table.ts
Labels: maintenance, semver-patch

#720 feat: add browser and default fields to exports
  package.json
  rollup.config.js
  scripts/measureSize.ts
  src/react-instrumentation/index.ts
  tests/utils/json-to-markdown-table.ts
Labels: feat, semver-minor

#732 chore(exports): add browser cjs export, use cjs extension in output
  package.json
  rollup.config.js
Labels: maintenance, semver-patch

#687 breaking: support uploading multiple source files for one single build
  README.md
  cli/README.md
  cli/snippet/fileBundleIDsSnippet.js
  cli/src/constants.ts
  cli/src/index.ts
  cli/src/processSourceFiles.ts
  cli/src/validateInput.ts
  demo/frontend/scripts/runDemo.sh
  src/constants/attributes.ts
  src/instrumentations/exceptions/GlobalExceptionInstrumentation/GlobalExceptionInstrumentation.test.ts
  src/instrumentations/exceptions/react/EmbraceErrorBoundary/EmbraceErrorBoundary.test.ts
  src/managers/EmbraceLogManager/EmbraceLogManager.test.ts
  src/managers/EmbraceLogManager/EmbraceLogManager.ts
  src/resources/constants/index.ts
  src/resources/types.ts
  src/resources/webSdkResource.test.ts
  src/resources/webSdkResource.ts
  src/sdk/initSDK.test.ts
  src/sdk/initSDK.ts
  src/sdk/types.ts
  src/utils/globalConfig.ts
  src/utils/index.ts
  tests/integration/tests/__golden__/chromium-next-latest-send-log.json
  tests/integration/tests/__golden__/chromium-next-latest-session.json
  tests/integration/tests/__golden__/chromium-vite-7-es2015-send-log.json
  tests/integration/tests/__golden__/chromium-vite-7-es2015-session.json
  tests/integration/tests/__golden__/chromium-vite-7-esnext-send-log.json
  tests/integration/tests/__golden__/chromium-vite-7-esnext-session.json
  tests/integration/tests/__golden__/chromium-webpack-5-es2015-send-log.json
  tests/integration/tests/__golden__/chromium-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/chromium-webpack-5-esnext-send-log.json
  tests/integration/tests/__golden__/chromium-webpack-5-esnext-session.json
  tests/integration/tests/__golden__/firefox-next-latest-send-log.json
  tests/integration/tests/__golden__/firefox-next-latest-session.json
  tests/integration/tests/__golden__/firefox-vite-7-es2015-send-log.json
  tests/integration/tests/__golden__/firefox-vite-7-es2015-session.json
  tests/integration/tests/__golden__/firefox-vite-7-esnext-send-log.json
  tests/integration/tests/__golden__/firefox-vite-7-esnext-session.json
  tests/integration/tests/__golden__/firefox-webpack-5-es2015-send-log.json
  tests/integration/tests/__golden__/firefox-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/firefox-webpack-5-esnext-send-log.json
  tests/integration/tests/__golden__/firefox-webpack-5-esnext-session.json
  tests/integration/tests/__golden__/webkit-next-latest-send-log.json
  tests/integration/tests/__golden__/webkit-next-latest-session.json
  tests/integration/tests/__golden__/webkit-vite-7-es2015-send-log.json
  tests/integration/tests/__golden__/webkit-vite-7-es2015-session.json
  tests/integration/tests/__golden__/webkit-vite-7-esnext-send-log.json
  tests/integration/tests/__golden__/webkit-vite-7-esnext-session.json
  tests/integration/tests/__golden__/webkit-webpack-5-es2015-send-log.json
  tests/integration/tests/__golden__/webkit-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/webkit-webpack-5-esnext-send-log.json
  tests/integration/tests/__golden__/webkit-webpack-5-esnext-session.json
Labels: maintenance, feat, semver-major, semver-minor, semver-patch, breaking

#740 chore(test): ensure storage methods return null instead of undefined
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.test.ts
  src/managers/EmbraceUserManager/EmbraceUserManager.test.ts
  src/processors/EmbraceSessionBatchedSpanProcessor/EmbraceSessionBatchedSpanProcessor.test.ts
  src/testUtils/InMemoryStorage/InMemoryStorage.ts
Labels: maintenance

#741 chore: lower node version requirement to v20 for cli
  cli/package.json
  package-lock.json
Labels: maintenance, semver-patch

#744 fix: adjust test to work on firefox
  src/exporters/EmbraceTraceExporter/EmbraceTraceExporter.test.ts
Labels: maintenance, fix, semver-patch

#771 docs: add CLAUDE.md
  CLAUDE.md
Labels: maintenance, semver-patch

#779 chore: update README with privacy faq and network instrumentation config for multiple instances
  README.md
  src/sdk/types.ts
Labels: maintenance, semver-patch

#789 refactor(cli): faster tools, lower node req to 18
  cli/.gitignore
  cli/.prettierrc.json
  cli/package.json
  cli/tsconfig.json
  package-lock.json
Labels: maintenance, semver-patch

#809 chore: update testing otel version
  src/sdk/initSDK.test.ts
Labels: maintenance, semver-patch

#810 chore: lock webpack 4 version, force otel-latest updates
  .github/dependabot.yml
Labels: maintenance, semver-patch

#811 chore: pin webpack 4 deps to current majors
  .github/dependabot.yml
Labels: maintenance, semver-patch

#806 feat(build): add build validation scripts
  .github/workflows/ci-nodejs.yml
  cli/package.json
  package-lock.json
  package.json
  scripts/validate-build.sh
  scripts/validate-cli.sh
Labels: maintenance, feat, semver-minor, semver-patch

#836 chore(deps): hoist all devDeps to root, clean up workspaces and dependabot
  .github/dependabot.yml
  cli/package.json
  demo/frontend-cdn/package.json
  demo/frontend-sdk/host/package.json
  demo/frontend-sdk/package-lock.json
  demo/frontend-sdk/package.json
  demo/frontend-sdk/sdk/package.json
  demo/frontend/package.json
  demo/webpack-example/.gitignore
  demo/webpack-example/README.md
  demo/webpack-example/index.html
  demo/webpack-example/package-lock.json
  demo/webpack-example/package.json
  demo/webpack-example/src/index.ts
  demo/webpack-example/tsconfig.json
  demo/webpack-example/webpack.config.js
  package-lock.json
  package.json
  tests/integration/README.md
  tests/integration/package.json
  tests/integration/platforms/next-latest/package.json
  tests/integration/platforms/vite-7/package.json
  tests/integration/platforms/vite-otel-latest/package.json
  tests/integration/platforms/webpack-4/package.json
  tests/integration/platforms/webpack-5/package.json
  tests/integration/platforms/webpack-5/webpack.config.es2015.mjs
  tests/integration/platforms/webpack-5/webpack.config.esnext.mjs
  tests/performance/package.json
Labels: maintenance, semver-patch

#832 EMBR-8655 chore: avoid running under restricted protocols
  src/sdk/initSDK.test.ts
  src/sdk/initSDK.ts
  src/sdk/types.ts
Labels: maintenance, semver-patch

#841 chore: update commander, looser webpack4 otel deps
  cli/package.json
  package-lock.json
  tests/integration/platforms/webpack-4/package.json
Labels: maintenance, semver-patch
