Repository embrace-io/embrace-web-sdk, pull requests merged in 2025-06, with the labels that each got.

#403 chore: support sourcemap uploads in the CDN case
  README.md
  src/resources/types.ts
  src/resources/webSdkResource.ts
  src/sdk/initSDK.test.ts
  src/sdk/initSDK.ts
  src/sdk/types.ts
Labels: maintenance, semver-patch

#407 feat: instrument react router v6 declarative
  REACT.md
  demo/frontend/package-lock.json
  demo/frontend/package.json
  demo/frontend/src/About.tsx
  demo/frontend/src/App.module.css
  demo/frontend/src/App.tsx
  demo/frontend/src/RoutingDemo/About.tsx
  demo/frontend/src/RoutingDemo/Home.tsx
  demo/frontend/src/RoutingDemo/Product.tsx
  demo/frontend/src/RoutingDemo/ProductComments.tsx
  demo/frontend/src/RoutingDemo/ReactRouterV4V5.tsx
  demo/frontend/src/RoutingDemo/ReactRouterV6Declarative.tsx
  demo/frontend/src/RoutingDemo/RoutingDemoContext.tsx
  demo/frontend/src/RoutingDemo/hooks.ts
  demo/frontend/src/index.css
  demo/frontend/src/main.tsx
  demo/frontend/src/otel.ts
  package-lock.json
  src/instrumentations/navigation/NavigationInstrumentation/index.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV5/createReactRouterNavigationInstrumentation.test.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV5/createReactRouterV5NavigationInstrumentation.test.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV5/createReactRouterV5NavigationInstrumentation.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV5/index.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV5/withEmbraceRoute.test.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV5/withEmbraceRoutingLegacy.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV6Declarative/createReactRouterV6DeclarativeNavigationInstrumentation.test.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV6Declarative/createReactRouterV6DeclarativeNavigationInstrumentation.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV6Declarative/index.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV6Declarative/types.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV6Declarative/withEmbraceRouting.test.ts
  src/instrumentations/navigation/NavigationInstrumentation/react/reactRouterV6Declarative/withEmbraceRouting.ts
  src/react/index.ts
  web-test-runner.config.js
Labels: feat, semver-minor

#422 fix: support node moduleResolution for older tsconfig settings for react-instrumentation
  demo/webpack-example/package-lock.json
  package.json
Labels: fix, semver-patch

#425 chore: automatically end navigation spans on session end
  src/api-sessions/api/SessionAPI/SessionAPI.test.ts
  src/api-sessions/api/SessionAPI/SessionAPI.ts
  src/api-sessions/manager/NoOpSpanSessionManager/NoOpSpanSessionManager.test.ts
  src/api-sessions/manager/NoOpSpanSessionManager/NoOpSpanSessionManager.ts
  src/api-sessions/manager/ProxySpanSessionManager/ProxySpanSessionManager.test.ts
  src/api-sessions/manager/ProxySpanSessionManager/ProxySpanSessionManager.ts
  src/api-sessions/manager/types.ts
  src/instrumentations/navigation/NavigationInstrumentation/NavigationInstrumentation.test.ts
  src/instrumentations/navigation/NavigationInstrumentation/NavigationInstrumentation.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.test.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
  src/managers/EmbraceSpanSessionManager/types.ts
Labels: maintenance, semver-patch

#438 chore: sync README.md with external docs
  REACT.md
Labels: maintenance, semver-patch

#458 chore: update lockfiles, ignore sonda output
  .gitignore
  demo/frontend/package-lock.json
  demo/webpack-example/package-lock.json
Labels: maintenance, semver-patch

#457 chore: use npm workspaces
  cli/package-lock.json
  cli/package.json
  demo/frontend-cdn/package-lock.json
  demo/frontend-cdn/package.json
  demo/frontend-cdn/scripts/runDemo.sh
  demo/frontend/package-lock.json
  demo/frontend/package.json
  demo/frontend/scripts/runDemo.sh
  demo/webpack-example/package-lock.json
  demo/webpack-example/package.json
  package-lock.json
  package.json
Labels: maintenance, semver-patch

#475 chore: add iife sourcemap
  .npmrc
  package-lock.json
  package.json
  rollup.config.js
Labels: maintenance, semver-patch

#440 EMBR-7484 feat: option for attributing previous URLs for core web vitals
  src/instrumentations/web-vitals/WebVitalsInstrumentation/WebVitalsInstrumentation.test.ts
  src/instrumentations/web-vitals/WebVitalsInstrumentation/WebVitalsInstrumentation.ts
  src/instrumentations/web-vitals/WebVitalsInstrumentation/types.ts
Labels: feat, semver-minor

#483 chore: suppress acceptable warnings
  rollup.config.js
Labels: maintenance, semver-patch

#484 chore: replace tsc with swc
  demo/frontend-cdn/.gitignore
  demo/frontend/index.html
  demo/webpack-example/.gitignore
  demo/webpack-example/package.json
  package-lock.json
  package.json
  rollup.config.js
  scripts/measureSize.ts
  tsconfig.types.json
Labels: maintenance, semver-patch

#485 chore: update instrumentation docs
  README.md
Labels: maintenance, semver-patch

#486 chore: cleanup before permanent props merge
  .github/workflows/ci-nodejs.yml
  demo/frontend/package.json
  demo/frontend/src/otel.ts
  package.json
  src/api-logs/api/LogAPI/LogAPI.ts
  src/api-sessions/api/SessionAPI/SessionAPI.ts
  src/api-sessions/index.ts
  src/api-sessions/manager/index.ts
  src/api-traces/api/TraceAPI/TraceAPI.ts
  src/api-traces/api/TraceAPI/types.ts
  src/api-users/api/UserAPI/UserAPI.ts
  src/constants/index.ts
  src/index.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.test.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
  src/managers/EmbraceTraceManager/EmbraceExtendedSpan.ts
  src/managers/EmbraceTraceManager/EmbraceTraceManager.ts
  src/managers/EmbraceTraceManager/index.ts
  src/managers/index.ts
  tsconfig.esm.json
Labels: maintenance, semver-patch

#487 chore: pin all 3rd-party GitHub actions
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
Labels: maintenance, semver-patch

#502 fix: test performance ci
  .github/workflows/ci-nodejs.yml
Labels: maintenance, fix, semver-patch

#500 EMBR-8143 feat: implement `emb.cold_start` session attribute
  src/constants/attributes.ts
  src/constants/index.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.test.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
  src/sdk/initSDK.test.ts
Labels: feat, semver-minor

#503 chore: add consistent type imports
  eslint.config.mjs
  package-lock.json
  package.json
  src/api-logs/api/LogAPI/LogAPI.test.ts
  src/api-logs/api/LogAPI/LogAPI.ts
  src/api-sessions/api/SessionAPI/SessionAPI.test.ts
  src/api-sessions/api/SessionAPI/SessionAPI.ts
  src/api-traces/api/TraceAPI/TraceAPI.test.ts
  src/api-traces/api/TraceAPI/TraceAPI.ts
  src/api-users/api/UserAPI/UserAPI.ts
  src/instrumentations/clicks/ClicksInstrumentation/ClicksInstrumentation.test.ts
  src/instrumentations/navigation/NavigationInstrumentation/NavigationInstrumentation.ts
  src/instrumentations/session/SpanSessionBrowserActivityInstrumentation/SpanSessionBrowserActivityInstrumentation.test.ts
  src/instrumentations/session/SpanSessionOnLoadInstrumentation/SpanSessionOnLoadInstrumentation.test.ts
  src/instrumentations/session/SpanSessionTimeoutInstrumentation/SpanSessionTimeoutInstrumentation.test.ts
  src/instrumentations/session/SpanSessionTimeoutInstrumentation/SpanSessionTimeoutInstrumentation.ts
  src/instrumentations/session/SpanSessionVisibilityInstrumentation/SpanSessionVisibilityInstrumentation.test.ts
  src/instrumentations/web-vitals/WebVitalsInstrumentation/WebVitalsInstrumentation.test.ts
  src/managers/EmbraceLogManager/EmbraceLogManager.test.ts
  src/managers/EmbraceLogManager/EmbraceLogManager.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
  src/managers/EmbraceUserManager/EmbraceUserManager.ts
  src/processors/EmbraceLogRecordProcessor/EmbraceLogRecordProcessor.ts
  src/processors/EmbraceProcessor/EmbraceProcessor.ts
  src/processors/IdentifiableSessionLogRecordProcessor/IdentifiableSessionLogRecordProcessor.ts
  src/processors/UserLogRecordProcessor/UserLogRecordProcessor.ts
  src/testUtils/FakeLogRecordProcessor/FakeLogRecordProcessor.ts
Labels: maintenance, semver-patch
