Repository embrace-io/embrace-web-sdk, pull requests merged in 2025-07, with the labels that each got.

#504 fix: support quotes in release body notes
  .github/workflows/release.yaml
Labels: fix, semver-patch

#505 fix: do not include package-lock.json in release
  .github/workflows/release.yaml
Labels: fix, semver-patch

#507 fix: support publishing web-cli with npm workspaces
  .github/workflows/ci-nodejs.yml
Labels: fix, semver-patch

#511 feat: explicitly export sdk to window
  rollup.config.js
Labels: maintenance, feat, semver-minor, semver-patch

#516 fix: correctly print release body
  .github/workflows/release.yaml
Labels: fix, semver-patch

#519 fix: correct use of bash variables in gha
  .github/workflows/ci-nodejs.yml
  .github/workflows/release.yaml
Labels: fix, semver-patch

#461 EMBR-7999 feat: data limit enforcement
  package-lock.json
  src/instrumentations/clicks/ClicksInstrumentation/ClicksInstrumentation.test.ts
  src/instrumentations/exceptions/GlobalExceptionInstrumentation/GlobalExceptionInstrumentation.test.ts
  src/instrumentations/exceptions/react/EmbraceErrorBoundary/EmbraceErrorBoundary.test.ts
  src/instrumentations/navigation/NavigationInstrumentation/NavigationInstrumentation.test.ts
  src/instrumentations/session/SpanSessionBrowserActivityInstrumentation/SpanSessionBrowserActivityInstrumentation.test.ts
  src/instrumentations/session/SpanSessionOnLoadInstrumentation/SpanSessionOnLoadInstrumentation.test.ts
  src/instrumentations/session/SpanSessionTimeoutInstrumentation/SpanSessionTimeoutInstrumentation.test.ts
  src/instrumentations/session/SpanSessionVisibilityInstrumentation/SpanSessionVisibilityInstrumentation.test.ts
  src/instrumentations/web-vitals/WebVitalsInstrumentation/WebVitalsInstrumentation.test.ts
  src/managers/EmbraceLimitManager/EmbraceLimitManager.ts
  src/managers/EmbraceLimitManager/constants.ts
  src/managers/EmbraceLimitManager/index.ts
  src/managers/EmbraceLimitManager/types.ts
  src/managers/EmbraceLogManager/EmbraceLogManager.test.ts
  src/managers/EmbraceLogManager/EmbraceLogManager.ts
  src/managers/EmbraceLogManager/types.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.test.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
  src/managers/EmbraceSpanSessionManager/types.ts
  src/managers/index.ts
  src/processors/EmbraceSessionBatchedSpanProcessor/EmbraceSessionBatchedSpanProcessor.test.ts
  src/processors/EmbraceSessionBatchedSpanProcessor/EmbraceSessionBatchedSpanProcessor.ts
  src/processors/EmbraceSessionBatchedSpanProcessor/types.ts
  src/processors/IdentifiableSessionLogRecordProcessor/IdentifiableSessionLogRecordProcessor.test.ts
  src/sdk/initSDK.test.ts
  src/sdk/initSDK.ts
  src/sdk/types.ts
  src/testUtils/fake-fetch/index.ts
  src/testUtils/index.ts
  src/testUtils/mockEntities/ReadableSpan.ts
Labels: feat, semver-minor

#523 chore: update log messages, fix typo
  demo/frontend/README.md
  demo/frontend/src/App.tsx
Labels: maintenance, semver-patch

#522 EMBR-7910 feat: track startup duration
  src/constants/attributes.ts
  src/constants/index.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
  src/sdk/initSDK.test.ts
  src/sdk/initSDK.ts
Labels: feat, semver-minor

#540 chore: repair package deps
  package-lock.json
  tests/bundle/vite-7/package-lock.json
  tests/bundle/webpack-5/package-lock.json
Labels: fix, semver-patch

#541 chore: add sourcemapDebugIds to rollup
  rollup.config.js
Labels: maintenance, semver-patch

#542 chore: export getNavigationInstrumentation
  src/index.ts
  src/instrumentations/index.ts
  src/instrumentations/navigation/index.ts
Labels: maintenance, semver-patch

#536 EMBR-7913 feat: add configuration options to clicks instrumentation for sensitive data
  src/instrumentations/clicks/ClicksInstrumentation/ClicksInstrumentation.test.ts
  src/instrumentations/clicks/ClicksInstrumentation/ClicksInstrumentation.ts
  src/instrumentations/clicks/ClicksInstrumentation/types.ts
  src/instrumentations/clicks/ClicksInstrumentation/utils.ts
Labels: feat, semver-minor

#543 chore: remove hardcoded app id
  demo/frontend-cdn/scripts/runDemo.sh
  demo/frontend/package.json
  demo/frontend/scripts/runDemo.sh
  package-lock.json
Labels: maintenance, semver-patch

#544 fix: re-running failing tests cache
  .github/workflows/ci-nodejs.yml
  tests/performance/tests/cdp-performance-tests.spec.ts
Labels: maintenance, semver-patch

#546 chore: update lockfile
  package-lock.json
Labels: maintenance, semver-patch

#548 fix: test expectation for startup duration
  src/sdk/initSDK.test.ts
Labels: maintenance, fix, semver-patch

#555 chore: fix typo
  src/sdk/setupDefaultInstrumentations.ts
  src/sdk/types.ts
Labels: maintenance, fix, semver-patch

#554 EMBR-8211 chore: resolve CI test run error
  web-test-runner.config.js
Labels: maintenance, semver-patch

#570 fix: remove debug id from builds
  rollup.config.js
Labels: maintenance, fix, semver-patch

#553 feat: add EmbraceConfigManager
  demo/frontend/src/otel.ts
  package.json
  src/managers/EmbraceConfigManager/EmbraceDynamicConfigManager.test.ts
  src/managers/EmbraceConfigManager/EmbraceDynamicConfigManager.ts
  src/managers/EmbraceConfigManager/constants.ts
  src/managers/EmbraceConfigManager/index.ts
  src/managers/EmbraceConfigManager/types.ts
  src/managers/EmbraceConfigManager/utils.ts
  src/managers/index.ts
  src/sdk/index.ts
  src/sdk/initSDK.test.ts
  src/sdk/initSDK.ts
  src/sdk/types.ts
  src/testUtils/fake-fetch/index.ts
  tests/integration/platforms/next-latest/src/lib/otel.ts
  tests/integration/platforms/vite-7/src/otel.ts
  tests/integration/platforms/webpack-5/src/otel.ts
  tests/integration/utils/run-e2e-tests.ts
  tests/integration/utils/test-with-mock-api.ts
Labels: feat, semver-minor

#580 fix: playwright dependabot again
  .github/dependabot.yml
Labels: fix, semver-patch

#581 chore: include user_agent.original resource attribute
  .github/dependabot.yml
  package-lock.json
  package.json
  src/resources/webSdkResource.test.ts
  src/resources/webSdkResource.ts
  src/sdk/initSDK.test.ts
  tests/integration/tests/__golden__/next-latest-send-log.json
  tests/integration/tests/__golden__/next-latest-session.json
  tests/integration/tests/__golden__/vite-7-es2015-send-log.json
  tests/integration/tests/__golden__/vite-7-es2015-session.json
  tests/integration/tests/__golden__/vite-7-esnext-send-log.json
  tests/integration/tests/__golden__/vite-7-esnext-session.json
  tests/integration/tests/__golden__/webpack-5-es2015-send-log.json
  tests/integration/tests/__golden__/webpack-5-es2015-session.json
  tests/integration/tests/__golden__/webpack-5-esnext-send-log.json
  tests/integration/tests/__golden__/webpack-5-esnext-session.json
  tests/integration/utils/test-with-mock-api.ts
Labels: maintenance, semver-patch

#574 chore: restrict more otel libs in dependabot
  .github/dependabot.yml
Labels: maintenance, semver-patch

#573 chore: create example with otel@latest
  tests/integration/.gitignore
  tests/integration/platforms/vite-otel-latest/.gitignore
  tests/integration/platforms/vite-otel-latest/README.md
  tests/integration/platforms/vite-otel-latest/eslint.config.js
  tests/integration/platforms/vite-otel-latest/index.html
  tests/integration/platforms/vite-otel-latest/package-lock.json
  tests/integration/platforms/vite-otel-latest/package.json
  tests/integration/platforms/vite-otel-latest/src/main.ts
  tests/integration/platforms/vite-otel-latest/tsconfig.json
  tests/integration/platforms/vite-otel-latest/vite.config.base.ts
  tests/integration/platforms/vite-otel-latest/vite.config.es2015.ts
  tests/integration/platforms/vite-otel-latest/vite.config.esnext.ts
  tests/integration/tests/build/vite-otel-latest-tests.test.ts
Labels: maintenance, semver-patch

#579 chore: implement sampling
  src/managers/EmbraceSDKFeaturesManager/EmbraceSDKFeaturesManager.test.ts
  src/managers/EmbraceSDKFeaturesManager/EmbraceSDKFeaturesManager.ts
  src/managers/EmbraceSDKFeaturesManager/index.ts
  src/managers/EmbraceSDKFeaturesManager/types.ts
  src/managers/index.ts
  src/sdk/initSDK.test.ts
  src/sdk/initSDK.ts
  src/testUtils/constants.ts
  src/testUtils/index.ts
  src/utils/index.ts
  src/utils/isDeviceIdSampled.test.ts
  src/utils/isDeviceIdSampled.ts
  tests/integration/utils/run-e2e-tests.ts
Labels: maintenance, semver-patch

#594 chore: watch types in dev mode
  package.json
Labels: maintenance, semver-patch

#596 chore: typo in prepublish script
  package.json
Labels: maintenance, semver-patch

#595 chore: add some missing types
  src/index.ts
Labels: maintenance, semver-patch

#593 chore: record session start reason
  DEVELOPING.md
  src/api-sessions/api/SessionAPI/SessionAPI.test.ts
  src/api-sessions/api/SessionAPI/SessionAPI.ts
  src/api-sessions/index.ts
  src/api-sessions/manager/ProxySpanSessionManager/ProxySpanSessionManager.test.ts
  src/api-sessions/manager/ProxySpanSessionManager/ProxySpanSessionManager.ts
  src/api-sessions/manager/index.ts
  src/api-sessions/manager/types.ts
  src/constants/attributes.ts
  src/constants/index.ts
  src/instrumentations/session/SpanSessionBrowserActivityInstrumentation/SpanSessionBrowserActivityInstrumentation.test.ts
  src/instrumentations/session/SpanSessionBrowserActivityInstrumentation/SpanSessionBrowserActivityInstrumentation.ts
  src/instrumentations/session/SpanSessionOnLoadInstrumentation/SpanSessionOnLoadInstrumentation.test.ts
  src/instrumentations/session/SpanSessionOnLoadInstrumentation/SpanSessionOnLoadInstrumentation.ts
  src/instrumentations/session/SpanSessionTimeoutInstrumentation/SpanSessionTimeoutInstrumentation.test.ts
  src/instrumentations/session/SpanSessionTimeoutInstrumentation/SpanSessionTimeoutInstrumentation.ts
  src/instrumentations/session/SpanSessionVisibilityInstrumentation/SpanSessionVisibilityInstrumentation.test.ts
  src/instrumentations/session/SpanSessionVisibilityInstrumentation/SpanSessionVisibilityInstrumentation.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.test.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
  src/sdk/initSDK.test.ts
  tests/integration/README.md
  tests/integration/tests/__golden__/chromium-next-latest-session.json
  tests/integration/tests/__golden__/chromium-vite-7-es2015-session.json
  tests/integration/tests/__golden__/chromium-vite-7-esnext-session.json
  tests/integration/tests/__golden__/chromium-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/chromium-webpack-5-esnext-session.json
  tests/integration/tests/__golden__/firefox-next-latest-session.json
  tests/integration/tests/__golden__/firefox-vite-7-es2015-session.json
  tests/integration/tests/__golden__/firefox-vite-7-esnext-session.json
  tests/integration/tests/__golden__/firefox-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/firefox-webpack-5-esnext-session.json
  tests/integration/tests/__golden__/webkit-next-latest-session.json
  tests/integration/tests/__golden__/webkit-vite-7-es2015-session.json
  tests/integration/tests/__golden__/webkit-vite-7-esnext-session.json
  tests/integration/tests/__golden__/webkit-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/webkit-webpack-5-esnext-session.json
Labels: maintenance, semver-patch

#608 chore: fix the dependabot logic for experimental packages
  .github/dependabot.yml
Labels: maintenance, fix, semver-patch

#607 chore: add browser support docs
  README.md
Labels: maintenance, semver-patch

#614 chore: update golden files
  package.json
  tests/integration/tests/__golden__/chromium-next-latest-send-log.json
  tests/integration/tests/__golden__/chromium-next-latest-session.json
  tests/integration/tests/__golden__/chromium-vite-7-es2015-send-log.json
  tests/integration/tests/__golden__/chromium-vite-7-es2015-session.json
  tests/integration/tests/__golden__/chromium-vite-7-esnext-send-log.json
  tests/integration/tests/__golden__/chromium-vite-7-esnext-session.json
  tests/integration/tests/__golden__/chromium-webpack-5-es2015-send-log.json
  tests/integration/tests/__golden__/chromium-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/chromium-webpack-5-esnext-send-log.json
  tests/integration/tests/__golden__/chromium-webpack-5-esnext-session.json
  tests/integration/tests/__golden__/firefox-next-latest-send-log.json
  tests/integration/tests/__golden__/firefox-next-latest-session.json
  tests/integration/tests/__golden__/firefox-vite-7-es2015-send-log.json
  tests/integration/tests/__golden__/firefox-vite-7-es2015-session.json
  tests/integration/tests/__golden__/firefox-vite-7-esnext-send-log.json
  tests/integration/tests/__golden__/firefox-vite-7-esnext-session.json
  tests/integration/tests/__golden__/firefox-webpack-5-es2015-send-log.json
  tests/integration/tests/__golden__/firefox-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/firefox-webpack-5-esnext-send-log.json
  tests/integration/tests/__golden__/firefox-webpack-5-esnext-session.json
  tests/integration/tests/__golden__/webkit-next-latest-send-log.json
  tests/integration/tests/__golden__/webkit-next-latest-session.json
  tests/integration/tests/__golden__/webkit-vite-7-es2015-send-log.json
  tests/integration/tests/__golden__/webkit-vite-7-es2015-session.json
  tests/integration/tests/__golden__/webkit-vite-7-esnext-send-log.json
  tests/integration/tests/__golden__/webkit-vite-7-esnext-session.json
  tests/integration/tests/__golden__/webkit-webpack-5-es2015-send-log.json
  tests/integration/tests/__golden__/webkit-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/webkit-webpack-5-esnext-send-log.json
  tests/integration/tests/__golden__/webkit-webpack-5-esnext-session.json
Labels: maintenance, semver-patch

#609 chore: fix commitlint command
  .lintstagedrc.mjs
  package.json
Labels: maintenance, fix, semver-patch

#617 chore: replace opentelemetry/sdk-trace-base with opentelemetry/sdk-trace-web
  package-lock.json
  package.json
  src/sdk/types.ts
  tests/integration/platforms/vite-7/src/otel.ts
  tests/integration/platforms/vite-otel-latest/README.md
  tests/integration/platforms/vite-otel-latest/package-lock.json
  tests/integration/platforms/vite-otel-latest/package.json
  tests/integration/platforms/vite-otel-latest/src/main.ts
  tests/integration/platforms/webpack-5/src/otel.ts
Labels: maintenance, semver-patch

#597 breaking: upgrade to otel 2
  demo/frontend-cdn/package.json
  demo/frontend/package.json
  package-lock.json
  package.json
  src/exporters/EmbraceLogExporter/EmbraceLogExporter.test.ts
  src/managers/EmbraceTraceManager/EmbraceTraceManager.test.ts
  src/processors/EmbraceLogRecordProcessor/EmbraceLogRecordProcessor.ts
  src/processors/IdentifiableSessionLogRecordProcessor/IdentifiableSessionLogRecordProcessor.ts
  src/processors/LogRecordScrubProcessor/LogRecordScrubProcessor.ts
  src/processors/UserLogRecordProcessor/UserLogRecordProcessor.ts
  src/resources/webSdkResource.ts
  src/sdk/initSDK.test.ts
  src/sdk/initSDK.ts
  src/testUtils/FakeLogRecordProcessor/FakeLogRecordProcessor.ts
  src/testUtils/mockEntities/IResource.ts
  src/testUtils/mockEntities/ReadableSpan.ts
  src/testUtils/mockEntities/Resource.ts
  src/testUtils/setupTestLogExporter/setupTestLogExporter.ts
  tests/integration/package.json
  tests/integration/platforms/next-latest/package-lock.json
  tests/integration/platforms/next-latest/package.json
  tests/integration/platforms/vite-7/package-lock.json
  tests/integration/platforms/vite-7/package.json
  tests/integration/platforms/vite-otel-latest/package-lock.json
  tests/integration/platforms/vite-otel-latest/package.json
  tests/integration/platforms/vite-otel-latest/src/main.ts
  tests/integration/platforms/webpack-5/eslint.config.js
  tests/integration/platforms/webpack-5/package-lock.json
  tests/integration/platforms/webpack-5/package.json
  tests/integration/utils/process-sonda-report.ts
  tests/integration/utils/test-with-mock-api.ts
Labels: semver-major, breaking

#615 EMBR-8435 chore: try and reduce integration test flakiness by bumping timeouts
  tests/integration/utils/run-e2e-tests.ts
Labels: maintenance, semver-patch

#616 chore: version bump job should also update goldens
  .github/workflows/release.yaml
Labels: maintenance, semver-patch

#619 chore: need ack installed in version bump job
  .github/workflows/release.yaml
Labels: maintenance, semver-patch

#620 chore: increase timeout for the version bump job
  .github/workflows/release.yaml
Labels: maintenance, semver-patch

#632 chore: housekeeping eslint/prettier
  eslint.config.mjs
  package.json
Labels: maintenance, semver-patch

#630 chore: optimize tsconfigs for bundlers
  tsconfig.json
  tsconfig.types.json
Labels: maintenance, semver-patch

#637 chore: use prefix in cdn demos
  demo/frontend-cdn/scripts/runDemo.sh
  demo/frontend/scripts/runDemo.sh
Labels: maintenance, fix, semver-patch

#636 chore: report sdk startup duration as `emb.sdk_startup_duration` attribute
  src/constants/attributes.ts
  src/constants/index.ts
  src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
  src/sdk/initSDK.test.ts
  src/sdk/initSDK.ts
  tests/integration/README.md
  tests/integration/tests/__golden__/chromium-next-latest-session.json
  tests/integration/tests/__golden__/chromium-vite-7-es2015-session.json
  tests/integration/tests/__golden__/chromium-vite-7-esnext-session.json
  tests/integration/tests/__golden__/chromium-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/chromium-webpack-5-esnext-session.json
  tests/integration/tests/__golden__/firefox-next-latest-session.json
  tests/integration/tests/__golden__/firefox-vite-7-es2015-session.json
  tests/integration/tests/__golden__/firefox-vite-7-esnext-session.json
  tests/integration/tests/__golden__/firefox-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/firefox-webpack-5-esnext-session.json
  tests/integration/tests/__golden__/webkit-next-latest-session.json
  tests/integration/tests/__golden__/webkit-vite-7-es2015-session.json
  tests/integration/tests/__golden__/webkit-vite-7-esnext-session.json
  tests/integration/tests/__golden__/webkit-webpack-5-es2015-session.json
  tests/integration/tests/__golden__/webkit-webpack-5-esnext-session.json
  tests/integration/utils/test-with-mock-api.ts
Labels: maintenance, semver-patch
